#!/bin/bash
# bash required to use `declare`

# URL to Project Euler's website
euler="https://projecteuler.net"

# HTML file to store Euler's response for debugging purposes
file_html="response.html"

# File with headers from a web browser with a valid session cookie
file_headers="headers.txt"

# File with cookies managed by functions from this file
file_cookies="cookies"

# PNG file to store Euler's captcha in
file_captcha="captcha.png"

# File to pass login and password to PE
file_credentials="credentials.txt"

# Captcha as jpg for jp2a
captcha_jpg="${file_captcha%.png}.jpg"


checkdep() {
	if ! hash $1 2>/dev/null; then
		echo "$1 not installed!"
		exit 1
	fi
}

# Check dependencies
checkdep jp2a
checkdep convert
checkdep curl

# Clear temporary / debug files
clear() {
	# -f to suppress file doesn't exist warnings
	rm -f "$file_captcha" "$captcha_jpg" "$file_html"
}

# Fetch captcha. PE server keeps track of ids of captcha you've requested and
# expects you to submit the last one, so use this function carefully
get_cap() {
	curl -s "$euler/captcha/show_captcha.php?" \
		-H @"$file_headers" --cookie "$file_cookies" -o "$file_captcha"

	convert "$file_captcha" "$captcha_jpg"
	jp2a "$captcha_jpg" -z --color --chars='..00xx@@'
}


# Download and show HTML for the account tab for debugging purposes
acc() {
	curl "$euler/account" \
	        --compressed -sH @"$file_headers" --cookie "$file_cookies" \
		| vim -
}

# Download a question from Project Euler
prob() {
	curl "$euler/problem=$1" -s \
	        | sed -n '/<div class="problem_content"/,/<\/div>/p' \
		| sed '1d; $d' \
		| sed 's/<[^>]*>//g'
}

# Get a random token to submit a solution to a problem
token() {
	result=$(curl "$euler/problem=$1" \
		--compressed -s -H @"$file_headers" --cookie "$file_cookies" \
		| sed 's/.*name=\"submit_token\" value=\"\([0-9a-z]*\)\".*/\1/p' -n)
	
	if [ -z "$result" ]
	then
	        echo "Either you're logged out or have already solved this problem"
		exit 1
	else
		echo "$result"
		exit 0
	fi
}

# Login to Project Euler using credentials from a file
login() {
	if [ ! -f $file_credentials ]; then
		echo "No credentials file $file_credentials!"
		exit 1
	fi

	user="$(head -1 $file_credentials | head -c -1)"
	pass="$(tail -1 $file_credentials | head -c -1)"

	curl "$euler/captcha/show_captcha.php?" \
	        --cookie-jar "$file_cookies" -o "$file_captcha" -s

	view_captcha

	read -p "Enter captcha:" cap

	curl "$euler/sign_in" \
	        --cookie "$file_cookies"  -L -o "$file_html" -s \
		-d "username=$user&password=$pass&captcha=$cap&sign_in=Sign+In"

	if grep -q "Sign in successful" "$file_html"; then
	        echo "Sign in successful"
		exit 0
	else
		echo "Something went wrong. Look at the content of $out_file"
		exit 1
	fi
}

# Submit a solution to a problem
submit() {
	if [ ! -f $file_headers ]; then
		echo "No headers file $file_headers!"
		exit 1
	elif [ ! -f $file_cookies ]; then
		echo "No cookies file $file_cookies!"
		exit 1
	fi

	read -p "Enter problem number:" prob
	tok=$(get_submit_token $prob)
	if [ $? -eq 1 ]; then
		echo "Unable to get a submit token"
		exit 1
	fi

	read -p "Enter answer:" ans

	fetch_captcha
	view_captcha
	read -p "Enter captcha:" cap
	rm "$file_captcha"


	data="guess_$prob=$ans&submit_token=$tok&captcha=$cap"

	curl "$euler/problem=$prob" \
		-H @"$file_headers" --cookie "$file_cookies" \
		-d "$data" \
		--compressed -Ls -o "$file_html"


	if grep -q "<p>Sorry, but the answer you gave appears to be incorrect.</p>" "$file_html"; then
		echo "Incorrect!"
		exit 1
	elif grep -q "<p>Congratulations, the answer you gave to problem $prob is correct.</p>" "$file_html"; then
		echo "Correct!"
		exit 0
	elif grep -q "An error occurred whilst trying to submit your guess<br>Please try again" "$file_html"; then
		echo "An error occured :("
		exit 1
	elif grep -q '<div id="message" class="noprint">The confirmation code you entered was not valid</div>' "$file_html"; then
		echo "Invalid captcha"
		exit 1
	else
		echo "Unknown error. Check $file_html and look what's going on"
		exit 1
	fi
}

if [[ $# -eq 0 ]] ;then
	echo "usage: euler <command>"
	echo ""
	echo "these are commands:"
	echo ""
	exit 1
fi

if declare -f "${1}__$2" >/dev/null; then
	func="${1}__$2"
	shift; shift    # pop $1 and $2 off the argument list
	"$func" "$@"    # invoke our named function w/ all remaining arguments
elif declare -f "$1" >/dev/null 2>&1; then
	"$@"
else
	echo "Neither function $1 nor subcommand ${1}__$2 recognized" >&2
	exit 1
fi

